In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

In [2]:
3. # a rank 0 tensor; a scalar with shape [],
[1., 2., 3.] # a rank 1 tensor; a vector with shape [3]
[[1., 2., 3.], [4., 5., 6.]] # a rank 2 tensor; a matrix with shape [2, 3]
[[[1., 2., 3.]], [[7., 8., 9.]]] # a rank 3 tensor with shape [2, 1, 3]

#Tensors are basically matrices

[[[1.0, 2.0, 3.0]], [[7.0, 8.0, 9.0]]]

You might think of TensorFlow Core programs as consisting of two discrete sections:

1) Building the computational graph (a tf.Graph).

2) Running the computational graph (using a tf.Session).



A Graph contains a set of tf.Operation objects, which represent units of computation; and tf.Tensor objects, which represent the units of data that flow between operations.

A Session object encapsulates the environment in which Operation objects are executed, and Tensor objects are evaluated.

A computational graph is a series of TensorFlow operations arranged into a graph. The graph is composed of two types of objects.

Operations (or "ops"): The nodes of the graph. Operations describe calculations that consume and produce tensors.
Tensors: The edges in the graph. These represent the values that will flow through the graph. Most TensorFlow functions return tf.Tensors.

In [5]:
# building a computational graph, we define graph 
# with tensors a and b, then use and operation of +

a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)

# total is an operation of add and produces a tensor add_1:0

Tensor("Const_4:0", shape=(), dtype=float32)
Tensor("Const_5:0", shape=(), dtype=float32)
Tensor("add_2:0", shape=(), dtype=float32)


In [6]:
writer = tf.summary.FileWriter('.')
writer.add_graph(tf.get_default_graph())

#This will produce an event file in the current directory with a 
# name in the following format:
# events.out.tfevents.{timestamp}.{hostname}

# Now, in a new terminal, launch TensorBoard with the following 
# shell command: tensorboard --logdir .

# localhost:6006 to open in browser
# SUPER COOL!

To evaluate tensors, instantiate a tf.Session object, informally known as a session. A session encapsulates the state of the TensorFlow runtime, and runs TensorFlow operations. If a tf.Graph is like a .py file, a tf.Session is like the python executable.

In [7]:
sess = tf.Session()
print(sess.run(total))

# When you request the output of a node with Session.run 
# TensorFlow backtracks through the graph and runs 
# all the nodes that provide input to the requested output node. 
# So this prints the expected value of 7.0:

7.0


In [8]:
print(sess.run({'ab':(a, b), 'total':total}))

# can edit what sess run outputs

{'ab': (3.0, 4.0), 'total': 7.0}


In [9]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))

# The result shows a different random value on each call to run, 
# but a consistent value during a single run 
# (out1 and out2 receive the same random input):

[0.29960835 0.15828967 0.80624497]
[0.52385473 0.64662826 0.37847185]
(array([1.0963836, 1.4823381, 1.6088932], dtype=float32), array([2.0963836, 2.482338 , 2.6088932], dtype=float32))


In [19]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

# A placeholder is a promise to provide a value later, 
# like a function argument.

print(sess.run(z, feed_dict={x: 3, y: 4.5}))
print(sess.run(z, feed_dict={x: [1, 3], y: [2, 4]}))

# We can evaluate this graph with multiple inputs by using
# the feed_dict argument of the run method to feed concrete 
# values to the placeholders:


# A way of feeding in multiple things into a session at a time
# or seperately

7.5
[3. 7.]


In [21]:
x = tf.constant(5, dtype=tf.float32)
y = tf.placeholder(tf.float32)
z = x + y
print(sess.run(z, feed_dict={x: 20, y: 4.5}))

# Also note that the feed_dict argument can be used to overwrite 
# any tensor in the graph. The only difference between placeholders 
# and other tf.Tensors is that placeholders throw an error 
# if no value is fed to them.

24.5


Placeholders work for simple experiments, but Datasets are the preferred method of streaming data into a model.

To get a runnable tf.Tensor from a Dataset you must first convert it to a tf.data.Iterator, and then call the Iterator's get_next method.

In [22]:
my_data = [
    [0, 1,],
    [2, 3,],
    [4, 5,],
    [6, 7,],
]
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()