In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

In [2]:
3. # a rank 0 tensor; a scalar with shape [],
[1., 2., 3.] # a rank 1 tensor; a vector with shape [3]
[[1., 2., 3.], [4., 5., 6.]] # a rank 2 tensor; a matrix with shape [2, 3]
[[[1., 2., 3.]], [[7., 8., 9.]]] # a rank 3 tensor with shape [2, 1, 3]

#Tensors are basically matrices

[[[1.0, 2.0, 3.0]], [[7.0, 8.0, 9.0]]]

You might think of TensorFlow Core programs as consisting of two discrete sections:

1) Building the computational graph (a tf.Graph).

2) Running the computational graph (using a tf.Session).



A Graph contains a set of tf.Operation objects, which represent units of computation; and tf.Tensor objects, which represent the units of data that flow between operations.

A Session object encapsulates the environment in which Operation objects are executed, and Tensor objects are evaluated.

A computational graph is a series of TensorFlow operations arranged into a graph. The graph is composed of two types of objects.

Operations (or "ops"): The nodes of the graph. Operations describe calculations that consume and produce tensors.
Tensors: The edges in the graph. These represent the values that will flow through the graph. Most TensorFlow functions return tf.Tensors.

In [3]:
# building a computational graph, we define graph 
# with tensors a and b, then use and operation of +

a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)

# total is an operation of add and produces a tensor add_1:0

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [4]:
writer = tf.summary.FileWriter('.')
writer.add_graph(tf.get_default_graph())

#This will produce an event file in the current directory with a 
# name in the following format:
# events.out.tfevents.{timestamp}.{hostname}

# Now, in a new terminal, launch TensorBoard with the following 
# shell command: tensorboard --logdir .

# localhost:6006 to open in browser
# SUPER COOL!

To evaluate tensors, instantiate a tf.Session object, informally known as a session. A session encapsulates the state of the TensorFlow runtime, and runs TensorFlow operations. If a tf.Graph is like a .py file, a tf.Session is like the python executable.

In [5]:
sess = tf.Session()
print(sess.run(total))

# When you request the output of a node with Session.run 
# TensorFlow backtracks through the graph and runs 
# all the nodes that provide input to the requested output node. 
# So this prints the expected value of 7.0:

7.0


In [6]:
print(sess.run({'ab':(a, b), 'total':total}))

# can edit what sess run outputs

{'ab': (3.0, 4.0), 'total': 7.0}


In [7]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))

# The result shows a different random value on each call to run, 
# but a consistent value during a single run 
# (out1 and out2 receive the same random input):

[0.7448479  0.77219486 0.9313885 ]
[0.25908327 0.28867412 0.30532455]
(array([1.9568231, 1.7788055, 1.0486269], dtype=float32), array([2.956823 , 2.7788055, 2.048627 ], dtype=float32))


In [8]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

# A placeholder is a promise to provide a value later, 
# like a function argument.

print(sess.run(z, feed_dict={x: 3, y: 4.5}))
print(sess.run(z, feed_dict={x: [1, 3], y: [2, 4]}))

# We can evaluate this graph with multiple inputs by using
# the feed_dict argument of the run method to feed concrete 
# values to the placeholders:


# A way of feeding in multiple things into a session at a time
# or seperately

7.5
[3. 7.]


In [9]:
x = tf.constant(5, dtype=tf.float32)
y = tf.placeholder(tf.float32)
z = x + y
print(sess.run(z, feed_dict={x: 20, y: 4.5}))

# Also note that the feed_dict argument can be used to overwrite 
# any tensor in the graph. The only difference between placeholders 
# and other tf.Tensors is that placeholders throw an error 
# if no value is fed to them.

24.5


Placeholders work for simple experiments, but Datasets are the preferred method of streaming data into a model.

class Dataset: Represents a potentially large set of elements.
class Iterator: Represents the state of iterating through a Dataset.
method make_one_shot_iterator: Creates an Iterator for enumerating the
    elements of this dataset.


In [10]:
my_data = [
    [0, 1,],
    [2, 3,],
    [4, 5,],
    [6, 7,],
]
# Ttf.Tensor from a Dataset to a tf.data.Iterator
slices = tf.data.Dataset.from_tensor_slices(my_data)
# then call the Iterator's get_next method
next_item = slices.make_one_shot_iterator().get_next()

# calling next_item, or slices.make_one_shot_iterator().get_next(),
# makes the iterator traverse my_data

In [16]:
sess = tf.Session()
print(sess.run(next_item))
print(sess.run(next_item))

[0 1]
[2 3]


In [17]:
sess = tf.Session()
while True:
  try:
    print(sess.run(next_item))
  except tf.errors.OutOfRangeError:
    break
# To iterate til end, or else throws error

[0 1]
[2 3]
[4 5]
[6 7]


In [21]:
# If the Dataset depends on stateful operations you may need to initialize 
# the iterator before using it, as shown below:

r = tf.random_normal([10,3])
dataset = tf.data.Dataset.from_tensor_slices(r)
iterator = dataset.make_initializable_iterator()
next_row = iterator.get_next()

sess.run(iterator.initializer) 
#iterator.initializer creates new iterator so can start from the top
while True:
  try:
    print(sess.run(next_row))
  except tf.errors.OutOfRangeError:
    break

[-0.3026785 -1.2253431 -0.0319563]
[ 0.5987973   0.34363747 -0.55804485]
[ 2.147123    0.7029443  -0.32105914]
[-0.5661651  1.3103114  1.9338412]
[-0.00511002 -0.34794495  1.238258  ]
[ 0.7268502  -0.35998338 -0.8058547 ]
[-1.1498337   0.44004586  0.50167704]
[-0.3328599   1.3193085   0.40100121]
[-0.06266612  1.8238652   0.56738615]
[-0.95596355 -0.47632757  0.6502408 ]


The following code creates a Dense layer that takes a batch of input vectors, and produces a single output value for each. To apply a layer to an input, call the layer as if it were a function. For example:

class Dense: This layer implements the operation: outputs =
    activation(inputs * kernel + bias)
class Layer: Base layer class. This is the class from which all layers 
    inherit, implementing common infrastructure functionality.

In [26]:
x = tf.placeholder(tf.float32, shape=[None, 3]) #example parameters
linear_model = tf.layers.Dense(units=1) #Layer
y = linear_model(x) #Output is layer acting on examples

# The layer contains variables that must be 
# initialized before they can be used. Because they say so

init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y, {x: [[1, 2, 3],[4, 5, 6]]})) # applying model on 2 inputs

# tf.layers.dense is a shortcut but bad for debugging

[[-1.1311809 ]
 [-0.86136436]]


class feature_columns: Think of feature columns as the intermediaries between raw data and Estimators.
function Input column: only accepts dense columns as inputs, Returns a dense Tensor as input layer based on given
    feature_columns.

In [29]:
#Making feature columns

# The easiest way to experiment with feature columns is using 
# the tf.feature_column.input_layer function. 
# This function only accepts dense columns as inputs, 
# so to view the result of a categorical column you must wrap it 
# in an tf.feature_column.indicator_column. For example:

features = {
    'sales' : [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']
}

#Defining columns
department_column = tf.feature_column.categorical_column_with_vocabulary_list(
        'department', ['sports', 'gardening'])
department_column = tf.feature_column.indicator_column(department_column)

columns = [
    tf.feature_column.numeric_column('sales'),
    department_column
]

inputs = tf.feature_column.input_layer(features, columns)
#Running the inputs tensor will parse the features into a batch of vectors.

In [31]:
# Feature columns can have internal state, like layers, so they often need to be initialized. 
# Categorical columns use lookup tables internally and these require a separate initialization op, 
# tf.tables_initializer.

var_init = tf.global_variables_initializer()
table_init = tf.tables_initializer()
sess = tf.Session()
sess.run((var_init, table_init))

# Once the internal state has been initialized you can run inputs like any other tf.Tensor:
print(sess.run(inputs))

# So basically column vectors 

[[ 1.  0.  5.]
 [ 1.  0. 10.]
 [ 0.  1.  8.]
 [ 0.  1.  9.]]
