In [1]:
from __future__ import division, absolute_import, division, print_function

import tensorflow as tf

tf.enable_eager_execution()

In [2]:
tf.executing_eagerly()

x = [[2.]]
m = tf.matmul(x, x) 
print("hello, {}".format(m))
# tf.Tensor objects reference concrete values instead of 
# symbolic handles to nodes in a computational graph.           COOL
# Since there isn't a computational graph to build and run later 
# in a session, it's easy to inspect results using print() or a debugger.

# TensorFlow math operations convert Python objects 
# and NumPy arrays to tf.Tensor objects. The tf.Tensor.numpy    THANK GOD
# method returns the object's value as a NumPy ndarray.

hello, [[4.]]


In [3]:
a = tf.constant([[1, 2],
                 [3, 4]])
print(a)

# Broadcasting support
b = tf.add(a, 1) #a+1
print(b)

# Operator overloading is supported
print(a * b)     #a.*b    NEAT!!
print("-------")

# Use NumPy values
import numpy as np
c = np.multiply(a, b)
print(c)

# Obtain numpy value from a tensor:
print(a.numpy())

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)
-------
[[ 2  6]
 [12 20]]
[[1 2]
 [3 4]]


In [4]:
import tensorflow.contrib.eager as tfe

w = tfe.Variable([[1.0]])
with tfe.GradientTape() as tape:
  loss = w * w

grad = tape.gradient(loss, [w])
print(grad) # getting the hang of it, you can print out details of any
            # tf object
    
# During eager execution, use tfe.GradientTape to trace 
# operations for computing gradients later.

Instructions for updating:
Use the retry module or similar alternatives.
[<tf.Tensor: id=31, shape=(1, 1), dtype=float32, numpy=array([[2.]], dtype=float32)>]
